version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://192.168.0.108:5432/keycloak
      - KC_DB=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=root
      - KC_HOSTNAME=192.168.0.108
      - KC_HOSTNAME_STRICT_HTTPS=false
      - JAVA_OPTS=-Dkeycloak.profile=preview
    command: start-dev --import-realm
    ports:
      - 8080:8080
    networks:
      - auth
    volumes: 
      - ./.k8s/keycloak/realm/data:/opt/keycloak/data/import
      # - ./.k8s/keycloak/keycloakify-starter/build_keycloak/src/main/resources/theme/keycloakify-starter:/opt/keycloak/themes/keycloakify-starter 
      # - ./.k8s/keycloak/keycloakify-starter/build_keycloak/src/main/resources/theme/keycloakify-starter-variant-1:/opt/keycloak/themes/keycloakify-starter-variant-1
 

  db:
    container_name: postgres
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: keycloak
        POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    env_file:
        - .env
    networks:
      - auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 3
    
networks:
  auth:
    driver: bridge