#!/bin/bash
# Gerar chave privada (para ser usada na aplicação principal)
openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048

# Gerar chave pública (para ser usada nos microsserviços)
openssl rsa -pubout -in private_key.pem -out public_key.pem
